v1 - задание 0
ArtAkaArt/dotnet-learning pull request #10
Opened 2022-02-05 17:23 UTC by ArtAkaArt

2022-02-05 21:58 UTC, navferty requested changes

2022-02-05 21:58 UTC, navferty commented on Sol0/Program.cs
> +            var directoryPath = Directory.GetCurrentDirectory() + "\\..\\..\\..\\Jsons\\";
в студии в свойствах json файла указать Content+CopyAlways, тогда файл будет скопирован в текущую папку, не нужно идти наверх

2022-02-05 21:58 UTC, navferty commented on Sol0/Program.cs
> +            if (FileCheck(directoryPath + "Units.json"))
можно использовать метод `Path.Combine`, для более надёжного конструирования пути к файлу

2022-02-05 21:58 UTC, navferty commented on Sol0/Program.cs
> +                                    .First();
`First` выкинет исключение, если ни одного элемента не получено. Хотя это действительно нештатная ситуация, в случае неконсистентных данных (по UnitId нет установки с таким Id), я бы предложил в этом случае кидать исключение с более понятным для пользователя сообщением, что именно не так

2022-02-07 13:08 UTC, navferty requested changes

2022-02-07 13:08 UTC, navferty commented on Sol0/Program.cs
> +            var directoryPath = Directory.GetCurrentDirectory() + "\\Jsons\\";
тут тоже можно переделать на `Path.Combine`

2022-02-07 13:08 UTC, navferty commented on Sol0/Program.cs
> +        static List<Unit> units = new List<Unit>();
FYI. в актуальной версии языка C# можно использовать сокращённую запись

```c#
static List<Unit> units = new();
```

2022-02-07 13:08 UTC, navferty commented on Sol0/Program.cs
> +                            .First();
Вместо try-catch над First можно изменить на вызов FirstOrDefault и проверять результат на null

2022-02-08 14:50 UTC, navferty commented on Sol0/Program.cs
> +            var directoryPath = Path.Combine(Directory.GetCurrentDirectory(), "Jsons\\");
а зачем слеш в конце? без него не работает?

2022-02-08 14:50 UTC, navferty commented on Sol0/Program.cs
> +                            .FirstOrDefault();
Вместо `.Where(Predicate).FirstOrDefault()` можно записать короче `.FirstOrDefault(Predicate)`

2022-02-11 21:50 UTC, navferty commented on Sol0/UserInterractions.cs
> +            if (unit is not null && Int32.TryParse(stats[0], out int stat1) && Int32.TryParse(stats[2], out int stat3))
вместо stat1 и stat3 я бы предложил сразу именовать осмысленно, например id, FactoryId

2022-02-11 21:50 UTC, navferty commented on Sol0/UserInterractions.cs
> +                    units.ForEach(t => Console.WriteLine($"Id = {t.Id}, Name = {t.Name}, FactoryId = {t.FactoryId}"));
Можно попробовать объявить интерфейс `IPrintable` с методом `Print()`, реализовать его в каждом из трех классов, и вызывать печать. Соответственно, детали вывода на печать переедут в нужный класс

2022-02-11 21:50 UTC, navferty commented on Sol0/UserInterractions.cs
> +            File.WriteAllText(Path.Combine(Directory.GetCurrentDirectory(),"..\\..\\..\\Jsons\\UnitsTst.json"), content, Encoding.UTF8);
Можно создавать json'ы например в папке %temp% или %appdata%. Впрочем, предлагаю забить и приступать к использованию СУБД =)

2022-02-11 21:50 UTC, navferty commented on Sol0/UserInterractions.cs
> +            if (unit is not null && Int32.TryParse(stats[0], out int stat1) && Int32.TryParse(stats[2], out int stat3))
Также вижу, что код выше (`ВВедите через запятую значения для Id, Name и FactoryId` и разбор ввода) дублируется. Возможно, стоит вынести его в отдельный метод

2022-02-13 11:21 UTC, navferty requested changes

2022-02-13 11:21 UTC, navferty commented on Sol0/UserInterractions.cs
> +        internal static string[] ReadUnitInput()
Может быть логику парсинга тоже перенести в этот метод? а чтобы отдавать сразу несколько значений из метода (id, name, factoryId), можно объявить например record с этими тремя полями, и возвращать его

2022-02-13 11:21 UTC, navferty commented on Sol0/IFacility.cs
> +        public void GetInfo();
Имя метода GetInfo может говорить о том, что оно возвращает информацию об объекте, однако в реальности оно не возвращает ничего, а печатает информацию в stdout. Рекомендую либо изменить имя (например PrintInfo - так имя явно говорит о том, что метод делает), либо изменить реализацию (например возвращать string с описанием, а на вызывающей стороне уже писать в `Console.WriteLine`)

2022-02-16 01:00 UTC, ArtAkaArt commented on Sol0/UserInterractions.cs
> +        internal static string[] ReadUnitInput()
Они не всегда парно используются, если я правильно предложение понял

2022-02-16 19:53 UTC, navferty requested changes

2022-02-16 19:53 UTC, navferty commented on Sol0/DBRequester.cs
> +            conn_param = $"Server=127.0.0.1;Port=5432;User Id={acc.AccName};Password={acc.Password};Database=Facilities;";
Рекомендую не увлекаться статическими переменными. Для класса `DBRequester` конфиг с логином/паролем является внешней зависимостью, и обычно принято такие зависимости получать через аргументы конструктора. Это позволит также переиспользовать этот же класс в веб-приложении, если перенести его в общую библиотеку классов. В консольном приложении его можно будет создавать через `new`, а вот в asp net уже использовать DI

2022-02-16 19:53 UTC, navferty commented on Sol0/DBRequester.cs
> +                var conn = new NpgsqlConnection(conn_param);
Ниже объект класса `NpgsqlCommand` оборачивается в `using`, чтобы освободить ресурсы, если что-то пойдёт не так. В то же время экземпляр `conn` класса `NpgsqlConnection` тоже реализует интерфейсы `IDisposable`/`IAsyncDisposable`, что говорит о необходимости позаботиться о правильном высвобождении их ресурсов. Да и в доках [приводится пример](https://www.npgsql.org/doc/), где он тоже в `using` обернут

2022-02-16 19:53 UTC, navferty commented on Sol0/DBRequester.cs
> +    internal class DBRequester
Обычно классы, которые реализуют слой доступа к данным, называют репозиториями (Repository). Имеет смысл переименовать, например, на `FacilityRepository` (или, если получится разбить без дублирования кода, на `UnitRepository` и `TankRepository`) - так читателю, ранее не знакомому с кодом, будет сразу понятна ответственность этого класса

2022-02-16 19:53 UTC, navferty commented on Sol0/DBRequester.cs
> +                    int nRows = comm.ExecuteNonQuery();
Хотя [задания на асинхронность](https://github.com/navferty/dotnet-learning#асинхронность) планируются далее, рекомендую по возможности использовать асинхронные версии методов для длительных операций. Да и задание можно уже сейчас посмотреть, возможно будет интересно изучить что под капотом у `Task` =)

2022-02-16 19:53 UTC, navferty commented on Sol0/DBRequester.cs
> +                    Console.WriteLine($"Id = {reader.GetInt32(0)}, Name = {reader.GetString(1)}, FactoryId = {reader.GetInt32(2)}");
Предлагаю ограничить ответственность этого класса только работой с данными в базе. То есть методы либо изменяют данные (например, принимая объект класса `Facility`/`Unit`), либо отдают данные в виде объектов нужных классов (тем более, для вывода на печать уже есть метод `PrintInfo`). Работу с вводом/выводом для пользователя можно выделить в отдельный сервис (предпочтительнее), либо вытащить просто в метод `Main`

2022-02-18 21:25 UTC, navferty approved these changes

2022-02-19 13:29 UTC, merged